version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: alpespartners_dijs
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  alpes-partners:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/alpespartners_dijs
      - REDIS_URL=redis://redis:6379
      - ENVIRONMENT=development
      - RECREATE_DB=false  # Cambiar a true solo si quieres eliminar todos los datos
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
    command: python run_flask.py

  celery-worker:
    build: .
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/alpespartners_dijs
      - REDIS_URL=redis://redis:6379
      - ENVIRONMENT=development
      - RECREATE_DB=false  # Cambiar a true solo si quieres eliminar todos los datos
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
    command: celery -A src.alpes_partners.infraestructura.celery_app worker --loglevel=info

volumes:
  postgres_data:
  redis_data:
